services:

  api:
    build:
      context: .
      dockerfile: Dockerfile.api
    container_name: binance-api
    restart: always
    env_file:
      - .env
    environment:
      - PYTHONPATH=/app/src
    ports:
      - "8000:8000"
    networks:
      - binance-network
    volumes:
      - ./src:/app/src

  dashboard:
    build:
      context: .
      dockerfile: Dockerfile.dashboard
    container_name: binance-dashboard
    restart: always
    environment:
      - API_HOST=api
    ports:
      - "8501:8501"
    depends_on:
      - api
    networks:
      - binance-network
    volumes:
      - ./dashboard:/app/dashboard

  airflow:
    image: apache/airflow:2.10.0-python3.12
    container_name: airflow-binance
    command: standalone
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow/src
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=polars motor beanie python-binance pydantic-settings nest_asyncio
    volumes:
      - ./airflow-local/dags:/opt/airflow/dags
      - ./airflow-local/logs:/opt/airflow/logs
      - ./airflow-local/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
    ports:
      - "8080:8080"
    networks:
      - binance-network

networks:
  binance-network:
    driver: bridge

volumes:
  mongo_data: