services:

  airflow:
    image: apache/airflow:2.10.0-python3.12
    container_name: airflow-binance
    command: standalone
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - PYTHONPATH=/opt/airflow/src
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=polars motor beanie python-binance pydantic-settings

    volumes:
      - ./airflow-local/dags:/opt/airflow/dags
      - ./airflow-local/logs:/opt/airflow/logs
      - ./airflow-local/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
    ports:
      - "8080:8080"

volumes:
  mongo_data: