services:
  mongodb:
    image: mongo:latest
    container_name: mongodb-binance
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  airflow:
    image: apache/airflow:2.10.0-python3.12
    container_name: airflow-binance
    command: standalone
    depends_on:
      - mongodb
    env_file:
      - .env
    environment:
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - MONGODB_URI=mongodb://mongodb:27017
      - PYTHONPATH=/opt/airflow/src
      - _AIRFLOW_WWW_USER_USERNAME=airflow
      - _AIRFLOW_WWW_USER_PASSWORD=airflow
      - _PIP_ADDITIONAL_REQUIREMENTS=polars motor beanie python-binance pydantic-settings

    volumes:
      - ./airflow-local/dags:/opt/airflow/dags
      - ./airflow-local/logs:/opt/airflow/logs
      - ./airflow-local/plugins:/opt/airflow/plugins
      - ./src:/opt/airflow/src
    ports:
      - "8080:8080"

volumes:
  mongo_data:
